# Generated by Django 4.2.8 on 2025-09-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('is_group', models.BooleanField(default=False, verbose_name='محادثة جماعية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('design_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='designs.designrequest', verbose_name='طلب التصميم')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('channel_name', models.CharField(blank=True, max_length=255, verbose_name='اسم القناة')),
                ('connection_count', models.IntegerField(default=0, verbose_name='عدد الاتصالات')),
                ('is_typing', models.BooleanField(default=False, verbose_name='يكتب')),
                ('typing_in_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation', verbose_name='يكتب في محادثة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حالة الاتصال',
                'verbose_name_plural': 'حالات الاتصال',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('design_request', 'طلب تصميم'), ('design_ready', 'تصميم جاهز'), ('design_delivered', 'تصميم مسلم'), ('message', 'رسالة جديدة'), ('payment', 'دفعة'), ('game_prize', 'جائزة لعبة'), ('system', 'إشعار نظام'), ('promotion', 'عرض ترويجي'), ('reminder', 'تذكير')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'مرتفع'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='نص الإجراء')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن المرتبط')),
                ('related_object_id', models.CharField(blank=True, max_length=255, verbose_name='معرف الكائن المرتبط')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='تم إرسال بريد')),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='تم إرسال إشعار فوري')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='chat_notifi_user_id_028bb1_idx'), models.Index(fields=['type', '-created_at'], name='chat_notifi_type_39102e_idx'), models.Index(fields=['priority', 'is_read'], name='chat_notifi_priorit_be81da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('audio', 'صوت'), ('system', 'نظام')], default='text', max_length=10, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/attachments/%Y/%m/%d/', verbose_name='المرفق')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المرفق')),
                ('attachment_size', models.IntegerField(blank=True, null=True, verbose_name='حجم المرفق')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('is_edited', models.BooleanField(default=False, verbose_name='معدلة')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوفة')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='المحادثة')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='رد على')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['conversation', 'sent_at'], name='chat_messag_convers_a33ce9_idx'), models.Index(fields=['sender', 'sent_at'], name='chat_messag_sender__93ff77_idx'), models.Index(fields=['is_read', 'sent_at'], name='chat_messag_is_read_019918_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conver_last_me_31163c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['design_request', 'is_active'], name='chat_conver_design__cc5d89_idx'),
        ),
    ]
