# Generated by Django 4.2.8 on 2025-09-16 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='designs.designcategory', verbose_name='الفئة الأم')),
            ],
            options={
                'verbose_name': 'فئة التصميم',
                'verbose_name_plural': 'فئات التصميم',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحجم')),
                ('width', models.IntegerField(help_text='بالبكسل', verbose_name='العرض')),
                ('height', models.IntegerField(help_text='بالبكسل', verbose_name='الارتفاع')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('print', 'طباعة'), ('general', 'عام')], default='general', max_length=50, verbose_name='المنصة')),
                ('is_custom', models.BooleanField(default=False, verbose_name='مخصص')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='معامل السعر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='designs.designcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'حجم التصميم',
                'verbose_name_plural': 'أحجام التصميم',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='الوصف التفصيلي')),
                ('custom_width', models.IntegerField(blank=True, help_text='للأحجام المخصصة فقط', null=True, verbose_name='العرض المخصص')),
                ('custom_height', models.IntegerField(blank=True, help_text='للأحجام المخصصة فقط', null=True, verbose_name='الارتفاع المخصص')),
                ('target_platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('print', 'طباعة'), ('multiple', 'متعدد')], default='facebook', max_length=50, verbose_name='منصة النشر')),
                ('urgency', models.CharField(choices=[('normal', 'عادي (4 أيام)'), ('medium', 'متوسط (2 يوم)'), ('urgent', 'مستعجل (1 يوم)')], default='normal', max_length=10, verbose_name='مستوى الاستعجال')),
                ('quality_level', models.CharField(choices=[('standard', 'عادي'), ('professional', 'احترافي'), ('premium', 'مميز')], default='standard', max_length=20, verbose_name='مستوى الجودة')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الأساسي')),
                ('urgency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الاستعجال')),
                ('quality_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الجودة')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('REVIEWING', 'قيد المراجعة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('READY', 'جاهز'), ('DELIVERED', 'تم التسليم'), ('ARCHIVED', 'مؤرشف'), ('CANCELLED', 'ملغي')], default='RECEIVED', max_length=20, verbose_name='الحالة')),
                ('client_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('designer_notes', models.TextField(blank=True, verbose_name='ملاحظات المصمم')),
                ('manager_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('client_satisfied', models.BooleanField(null=True, verbose_name='رضا العميل')),
                ('revision_count', models.IntegerField(default=0, verbose_name='عدد التعديلات')),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='روابط أو مسارات الصور المرجعية', verbose_name='صور مرجعية')),
                ('final_designs', models.JSONField(blank=True, default=list, help_text='روابط أو مسارات التصاميم النهائية', verbose_name='التصاميم النهائية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_designs', to=settings.AUTH_USER_MODEL, verbose_name='المصمم المعين')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.designcategory', verbose_name='فئة التصميم')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.designsize', verbose_name='الحجم')),
            ],
            options={
                'verbose_name': 'طلب تصميم',
                'verbose_name_plural': 'طلبات التصميم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reference', 'صورة مرجعية'), ('draft', 'مسودة'), ('final', 'نهائي'), ('revision', 'تعديل')], default='reference', max_length=20, verbose_name='نوع المرفق')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='الملف')),
                ('original_name', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.IntegerField(help_text='بالبايت', verbose_name='حجم الملف')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='designs.designrequest', verbose_name='الطلب')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('quality_rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='جودة التصميم')),
                ('speed_rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='سرعة التنفيذ')),
                ('communication_rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التواصل')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المصمم')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='designs.designrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'client')},
            },
        ),
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('quality_multiplier_standard', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='معامل الجودة العادية')),
                ('quality_multiplier_professional', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='معامل الجودة الاحترافية')),
                ('quality_multiplier_premium', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='معامل الجودة المميزة')),
                ('urgency_multiplier_normal', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='معامل السرعة العادية')),
                ('urgency_multiplier_medium', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='معامل السرعة المتوسطة')),
                ('urgency_multiplier_urgent', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='معامل السرعة العاجلة')),
                ('bulk_discount_threshold', models.IntegerField(default=5, help_text='عدد الطلبات للحصول على الخصم', verbose_name='حد الخصم الجماعي')),
                ('bulk_discount_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='نسبة الخصم الجماعي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings', to='designs.designcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'إعداد السعر',
                'verbose_name_plural': 'إعدادات الأسعار',
                'unique_together': {('category',)},
            },
        ),
        migrations.AddIndex(
            model_name='designrequest',
            index=models.Index(fields=['status', 'created_at'], name='designs_des_status_a97ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='designrequest',
            index=models.Index(fields=['client', 'status'], name='designs_des_client__cb1adb_idx'),
        ),
        migrations.AddIndex(
            model_name='designrequest',
            index=models.Index(fields=['assigned_designer', 'status'], name='designs_des_assigne_ed00d7_idx'),
        ),
        migrations.AddIndex(
            model_name='designrequest',
            index=models.Index(fields=['request_number'], name='designs_des_request_191cdd_idx'),
        ),
    ]
