# Generated by Django 4.2.8 on 2025-09-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelOfFortune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='عجلة الحظ اليومية', max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('segments', models.JSONField(default=list, help_text='قائمة بالقطاعات وجوائزها', verbose_name='قطاعات العجلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('max_spins_per_day', models.IntegerField(default=1, verbose_name='الحد الأقصى للدورات يومياً')),
                ('requires_purchase', models.BooleanField(default=False, verbose_name='يتطلب شراء')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للشراء')),
                ('total_spins', models.IntegerField(default=0, verbose_name='إجمالي الدورات')),
                ('total_prizes_given', models.IntegerField(default=0, verbose_name='إجمالي الجوائز الممنوحة')),
                ('wheel_style', models.JSONField(blank=True, default=dict, help_text='CSS وإعدادات التصميم', verbose_name='تصميم العجلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عجلة الحظ',
                'verbose_name_plural': 'عجلات الحظ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اللعبة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('original_image', models.ImageField(upload_to='puzzles/originals/%Y/%m/', verbose_name='الصورة الأصلية')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='puzzles/thumbnails/%Y/%m/', verbose_name='الصورة المصغرة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل (3×3)'), ('medium', 'متوسط (4×4)'), ('hard', 'صعب (5×5)'), ('expert', 'خبير (6×6)')], default='medium', max_length=20, verbose_name='مستوى الصعوبة')),
                ('grid_size', models.IntegerField(default=4, verbose_name='حجم الشبكة')),
                ('time_limit', models.IntegerField(default=300, help_text='بالثواني (0 = بدون حد زمني)', verbose_name='الحد الزمني')),
                ('points_reward', models.IntegerField(default=10, verbose_name='نقاط المكافأة')),
                ('bonus_time_threshold', models.IntegerField(default=60, help_text='إكمال في أقل من هذا الوقت للحصول على مكافأة', verbose_name='حد الوقت للمكافأة الإضافية')),
                ('bonus_points', models.IntegerField(default=5, verbose_name='نقاط المكافأة الإضافية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_daily', models.BooleanField(default=False, verbose_name='لعبة اليوم')),
                ('active_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('total_plays', models.IntegerField(default=0, verbose_name='إجمالي مرات اللعب')),
                ('total_completions', models.IntegerField(default=0, verbose_name='إجمالي الإكمالات')),
                ('average_time', models.FloatField(default=0, verbose_name='متوسط الوقت')),
                ('best_time', models.FloatField(blank=True, null=True, verbose_name='أفضل وقت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'لعبة بازل',
                'verbose_name_plural': 'ألعاب البازل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.JSONField(default=dict, verbose_name='النتيجة')),
                ('prize_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الجائزة')),
                ('prize_value', models.CharField(blank=True, max_length=100, verbose_name='قيمة الجائزة')),
                ('prize_claimed', models.BooleanField(default=False, verbose_name='تم استلام الجائزة')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('spin_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدورة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='games.wheeloffortune', verbose_name='العجلة')),
            ],
            options={
                'verbose_name': 'دورة عجلة',
                'verbose_name_plural': 'دورات العجلة',
                'ordering': ['-spin_date'],
                'indexes': [models.Index(fields=['user', 'spin_date'], name='games_wheel_user_id_090fb5_idx'), models.Index(fields=['wheel', 'spin_date'], name='games_wheel_wheel_i_7f4a34_idx')],
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('completion_time', models.FloatField(blank=True, help_text='بالثواني', null=True, verbose_name='وقت الإكمال')),
                ('moves_count', models.IntegerField(default=0, verbose_name='عدد الحركات')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('points_earned', models.IntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('bonus_earned', models.BooleanField(default=False, verbose_name='حصل على مكافأة')),
                ('game_state', models.JSONField(blank=True, default=dict, help_text='حفظ حالة اللعبة للاستكمال لاحقاً', verbose_name='حالة اللعبة')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.puzzlegame', verbose_name='اللعبة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محاولة بازل',
                'verbose_name_plural': 'محاولات البازل',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='games_puzzl_user_id_d6b5db_idx'), models.Index(fields=['puzzle', 'is_completed'], name='games_puzzl_puzzle__e1efb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('wheel', 'عجلة الحظ'), ('puzzle', 'البازل'), ('overall', 'الإجمالي')], max_length=20, verbose_name='نوع اللعبة')),
                ('period', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('alltime', 'دائم')], max_length=20, verbose_name='الفترة')),
                ('score', models.IntegerField(default=0, verbose_name='النقاط')),
                ('rank', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('games_played', models.IntegerField(default=0, verbose_name='عدد الألعاب')),
                ('best_time', models.FloatField(blank=True, null=True, verbose_name='أفضل وقت')),
                ('period_start', models.DateTimeField(verbose_name='بداية الفترة')),
                ('period_end', models.DateTimeField(verbose_name='نهاية الفترة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'لوحة متصدرين',
                'verbose_name_plural': 'لوحات المتصدرين',
                'ordering': ['game_type', 'period', 'rank'],
                'indexes': [models.Index(fields=['game_type', 'period', 'rank'], name='games_leade_game_ty_9d49bf_idx'), models.Index(fields=['user', 'game_type', 'period'], name='games_leade_user_id_54a676_idx')],
                'unique_together': {('user', 'game_type', 'period', 'period_start')},
            },
        ),
    ]
